public class qfour {
    private static String input;
    
    public Boolean test(String input)
    {
        if(input ==' ')
        {
            return null;
        }
        else if(input == 'Test')
        {
            return TRUE;
        }
        else if(input == 'Salesforce')
        {
            return true;
        }
        else
        {
            return false;
        }
    }
}